citizen/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('citizenapp.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_URL)

citizenapp/urls.py
from django.conf.urls import url
from . import views
app_name = 'citizenapp'

urlpatterns = [
	url(r'^$',views.citizenAdd, name = 'citizenAdd'),
	url(r'^citizenList/$', views.citizenList, name = 'citizenList'),
	url(r'^citizenList/delete/', views.citizenDelete, name = 'citizenDelete'),
	url(r'^get_citizen', views.get_citizen, name = 'get_citizen'),
	url(r'^file_upload', views.file_upload, name = 'file_upload'),
	url(r'^citizenList/update/', views.citizenUpdate, name = 'citizenUpdate'),

]

citizenapp/models.py
from django.db import models

class Citizen(models.Model):
	first_name = models.CharField(max_length = 20)
	last_name = models.CharField(max_length = 30)
	birth_date = models.DateField(null=True)
	email = models.CharField(max_length=50, unique=True)
	mobile = models.CharField(max_length=15)
	address = models.CharField(max_length=500)
	city = models.CharField(max_length=50)
	pincode = models.CharField(max_length=6)
	qualification = models.CharField(max_length=90)
	document_type = models.CharField(max_length=50)

citizenapp/views.py
from .models import Citizen
from django.shortcuts import redirect,render,get_object_or_404
from django import forms
from django.core.files.storage import FileSystemStorage
import json
from django.http import JsonResponse,Http404, HttpResponse
from django.conf import settings
import os
from django.core import serializers
from datetime import datetime

'''  for Get the all citizens  '''
def get_citizen(request):
	data = {}
	citizens = Citizen.objects.all()
	data['all_citizens'] = citizens
	resp = []
	if citizens:
		for each in list(citizens):
			temp = {}
			temp['first_name'] = each.first_name
			temp['last_name'] = each.last_name
			temp['birth_date'] = datetime.strftime(each.birth_date, '%Y-%m-%d')
			temp['email'] = each.email
			temp['mobile'] = each.mobile
			temp['city'] = each.city
			temp['address'] = each.address
			temp['qualification'] = each.qualification
			temp['pk'] = each.pk
			temp['pincode'] = each.pincode
			resp.append(temp)
	data['all_citizens'] = resp
	print data
	return HttpResponse(json.dumps(data), content_type='application/json')
	# return JsonResponse(data)

def citizenList(request,template_name='list.html'):
	return render(request,template_name)


'''  for file upload '''
def file_upload(request,template_name='common_form.html'):
	if request.method == "POST":
		# print request.body
		# print request.FILES['document']
		for name, file in request.FILES.iteritems():
			current_file = os.path.join(settings.BASE_DIR, 'media', name)
			if os.path.exists(current_file): 
				os.remove(current_file)
	   		fs = FileSystemStorage()
			filename = fs.save(name, file)
			uploaded_file_url = fs.url(filename)
			# print uploaded_file_url

'''  for create citizen '''
def citizenAdd(request,template_name='common_form.html'):
	if request.method == "POST":
		print request.body
		# print request.FILES
		data = json.loads(request.body)
		birth_date = data['birth_date'].split('T')[0]
		birth_date = datetime.strptime(birth_date, '%Y-%m-%d')
		data['birth_date'] = birth_date
		print birth_date
		citizen = Citizen(**data)
		# print citizen.first_name
		# citizen = all_data
		citizen.save()
		responseData = {'message':'success','status' :200, 'redirect' :'citizenList/'}
		return JsonResponse(responseData)
	return render(request,template_name)

''' for updating the citizen record '''
def citizenUpdate(request,template_name = 'update_form.html'):

	if request.method == 'POST':
		responseData = {}
		data = json.loads(request.body)
		# print data
		data.pop('pk',None)
		birth_date = data['birth_date'].split('T')[0]
		birth_date = datetime.strptime(birth_date, '%Y-%M-%d')
		data['birth_date'] = birth_date
		p=Citizen.objects.get(pk=data['id'])
		# print p
		if p:
			# print "inside p"
			Citizen.objects.filter(pk=data['id']).update(**data)
			responseData = {'redirect' :''}
			# print responseData
		return JsonResponse(responseData)

''' for deleting the citizen record '''
def citizenDelete(request):
	data = json.loads(request.body)
	# print data['pk']
	citizen = get_object_or_404(Citizen,pk=data['pk'])
	if request.method == 'POST':
		citizen.delete()

		citizens = Citizen.objects.all()
		resp = []
		if citizens:
			for each in list(citizens):
				temp = {}
				temp['first_name'] = each.first_name
				temp['email'] = each.email
				temp['mobile'] = each.mobile
				temp['city'] = each.city
				temp['qualification'] = each.qualification
				temp['pk'] = each.pk
				resp.append(temp)
		data['all_citizens'] = resp
		return HttpResponse(json.dumps(data), content_type='application/json')
	return redirect('citizenapp:citizenList')

citizenapp/templates/base.html
<!DOCTYPE html>
<html ng-app="citizen_module">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}CitizenApp{% endblock %}</title>
	{% load staticfiles %}
	<meta charset="utf-8">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/2.0/css/font-awesome.css" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle='collapse' data-target= "#topnav">
					<span class='icon-bar'></span>
					<span class='icon-bar'></span>
					<span class='icon-bar'></span>
				</button>
				<a class="navbar-brand" href="">Home</a>
			</div>
			<div class="collapse navbar-collapse" id="topnav">
				<ul class="nav navbar-nav">
					<li>
						<a href="{% url 'citizenapp:citizenList' %}">
							<span class='glyphicon glyphicon-user' aria-hidden='true'></span>&nbsp;
							All Citizens
						</a>
					</li>
					<li>
						<a href="{% url 'citizenapp:citizenAdd' %}">
							<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>&nbsp; 
							Add Citizens
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	{% block body%}
	{% endblock %}
</body>
{% block script %}
<script src="{% static 'js/angular.js' %}" type="text/javascript"></script>
<script src="{% static 'js/citizen_angular.js' %}" type="text/javascript"></script>
{% endblock %}
</html>

citizenapp/templates/common_form.html
{% extends 'base.html' %}
{% block title %}Citizen Form{% endblock %}
{% block body %}
	<div class= "container-fluid" ng-controller = 'citizen_controller'>
		<div class= "row">
			<div class="col-sm-0 col-lg-2 col-md-2"> 
				
			</div>
			<div class="col-sm-12 col-lg-8 col-md-8">
				<div class="panel panel-default">
				<div class="panel-heading"><strong>Citizen Registration</strong></div>
					<div class="panel-body">
						<form name = "citizenform" enctype="multipart/form-data">
						{% csrf_token %}
							<div class="form-row">
							    <div class="form-group col-md-6">
							      <label for="first_name">First Name</label>
							      <input type="text" class="form-control" name = "first_name" id="first_name" ng-model="data.first_name" ng-required="true">
							    </div>
							    <div class="form-group col-md-6">
							      <label for="last_name">Last Name</label>
							      <input type="" class="form-control" id="last_name" name = "last_name" ng-model="data.last_name" ng-required="true">
							    </div>
							</div>
							<div class="form-row">
							    <div class="form-group col-md-6">
							      <label for="email">Email</label>
							      <input type="email" class="form-control" id="email" name="email" ng-model = "data.email" ng-required="true">
							    </div>
							    <div class="form-group col-md-6">
							      <label for="Birth_Date">Birth Date</label>
							      <input type="date" class="form-control" id="birth_Date" name="Birth_Date" ng-model="data.birth_date" ng-required="true">
							    </div>
							</div>
							<div class="form-row">
							    <div class="form-group col-md-6">
							      <label for="city">City</label>
							      <input type="text" class="form-control" id="city" name="city" 
							      ng-model="data.city" ng-required="true">
							    </div>
							    <div class="form-group col-md-6">
						      		<label for="pincode">pincode</label>
						      		<input type="text" class="form-control" id="pincode" name="pincode" ng-model="data.pincode" ng-required="true" maxlength="6"ng-pattern="/^[0-9]{0,7}$/">
								     <span ng-show="citizenform.pincode.$error.pattern" color='red'>Not a valid Pincode!</span>
						    	</div>
							</div>
							<div class="form-row">
								<div class="form-group col-md-12">
								    <label for="Address">Address</label>
								    <input type="text" class="form-control" id="Address" name="address" ng-model = "data.address" ng-required="true">
								</div>
							</div>
							<div class="form-row">
								<div class="form-group col-md-6">
								      <label for="Mobile">Mobile</label>
								      <input type="text" class="form-control" id="Mobile" name="mobile" ng-model="data.mobile" ng-required="true" maxlength="10" ng-pattern="/^[0-9]{0,10}$/">
								      <span ng-show="citizenform.mobile.$error.pattern" color='red'>Not a valid number!</span>
								</div>
							    <div class="form-group col-md-6">
							      <label for="Qualification">Qualification</label>
							      <input type="text" class="form-control" id="Qualification" name="qualification" ng-model="data.qualification" ng-required="true">
							    </div>
						    </div>
						    <div class="form-row">
							    <div class="form-group col-md-4">
							      <label for="document"> Document Type</label>
										
									<select class="form-control" name="document_type" ng-model="data.document_type" ng-required="true">
								      <option>Select</option>
								      <option value="aadhar">Aadhar</option>
								      <option value="voter_id">Voter ID</option>
								      <option value="ration_card">Ration Card</option>
								      <option value="ration_card">Pan Card</option>
								    </select>

	    						</div>

	    						<div class="form-group col-md-6">
									<label for="document">Upload Document</label>
									<input type="file" class="form-control" name="document" file-model="myFile" ng-required="true" />
							      
							    </div>
							    <div class="form-group col-md-2" style="padding-top:22px">
							    	<button type="submit" ng-click = "citizenform.$valid && uploadFile(data.first_name, 'document')" class="btn btn-warning">Upload</button>
							    </div>
	    					</div>

	    					<div class='form-row'>
	    						<div class="form-group col-md-6">
									<label for="document">Upload Photo</label>
									<input type="file" class="form-control" name="document" file-model="myPhoto" ng-required="true" />
								</div>
							    <div class="form-group col-md-6" style="padding-top:22px">
							    	<button type="submit" ng-click = "citizenform.$valid && uploadFilePhoto(data.first_name, 'photo')" class="btn btn-warning">Upload</button>
					    		</div>
	    					</div>
	    					
						    <!-- <div class="form-row text-center"> -->
							    <div class="form-group text-center">
							    <button type="submit" ng-click = "citizenform.$valid && add_citizen()" class="btn btn-primary btn-block">Submit</button>
							    </div>
						    <!-- </div>  -->
						</form>
						<!-- <div class="form-row pull-right">
							    <div class="form-group col-md-6">
							    <button type="submit" ng-click = "add_citizen()" class="btn btn-primary">Submit</button>
							    </div>
						    </div> -->
					</div>
				</div>	
			</div>
		</div>
		<div class="col-sm-0 col-lg-2 col-md-2">
		</div>
	</div>
{% endblock %}

citizenapp/templates/list.html
{% extends 'base.html' %}
{% block title %}Citizen Form{% endblock %}
{% block body %}
<div class= "container-fluid" ng-controller = 'citizen_controller'>
	<table class="table table-bordered">
		<div class="row">
			<div class="pull-right col-md-4 col-lg-4 col-sm-4">
				 <input type="text" ng-model="search" class="form-control" placeholder="Search In Table">
			</div>
		</div><br>
	    <thead>
	      <tr>
	      	<th class="id">Name&nbsp;<a ng-click="sort_by('first_name')"><i class="icon-sort"></i></a></th>
	        <th>Email&nbsp;<a ng-click="sort_by('email')"><i class="icon-sort"></i></a>
	        </th>
	        <th>Mobile&nbsp;<a ng-click="sort_by('mobile')"><i class="icon-sort"></i></a>
	        </th>
	        <th>City&nbsp;<a ng-click="sort_by('city')"><i class="icon-sort"></i></a>
	        </th>
	        <th>Qualification&nbsp;<a ng-click="sort_by('qualification')"><i class="icon-sort"></i></a>
	        </th>
	        <th>Action</th>
	      </tr>
    	</thead>
	    <tbody>
	  
	      <tr ng-repeat="temp in all_citizen | filter:search | orderBy:sortingOrder:reverse">
	        <td>{[ temp.first_name]} {[temp.last_name]}</td>
	        <td>{[ temp.email ]}</td>
	        <td>{[ temp.mobile ]}</td>
	        <td>{[ temp.city ]}</td>
	        <td>{[ temp.qualification]}</td>
	        <td>
				<button type="submit" data-toggle="modal" ng-click = "open_modal(temp)" class="btn btn-warning btn-sm">
				    <span class="glyphicon glyphicon-edit"></span>
				</button>
			    
				<button type="submit" ng-click = "citizenDelete(temp.pk)" class="btn btn-warning btn-sm">
				    <span class="glyphicon glyphicon-trash"></span>
				</button>
			   
		    </td>
	      </tr>
	   
	    </tbody>
        <tfoot>
           
        </tfoot>
    </table>
    <!-- MODAL -->
	<div id="updateModal" class="modal fade" role="dialog">
		<div class="modal-dialog">
	    <!-- Modal content-->
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	        <h4 class="modal-title">Update Citizen</h4>
	      </div>
	      <div class="modal-body">
		<div class= "row">
			
			<div class="col-sm-12 col-lg-12 col-md-12">
				<div class="panel panel-default">
				<!-- <div class="panel-heading"><strong>Citizen Registration</strong></div> -->
					<div class="panel-body">
						<form name = "citizenform" enctype="multipart/form-data">
						{% csrf_token %}
							<div class="form-row">
							    <div class="form-group col-md-6">
							      <label for="first_name">First Name</label>
							      <input type="text" class="form-control" name = "first_name" id="first_name"  ng-model="single_citizen.first_name" ng-required="true">
							    </div>
							    <div class="form-group col-md-6">
							      <label for="last_name">Last Name</label>
							      <input type="" class="form-control" id="last_name" name = "last_name" ng-model="single_citizen.last_name" ng-required="true">
							    </div>
							</div>
							<div class="form-row">
							    <div class="form-group col-md-6">
							      <label for="email">Email</label>
							      <input type="email" class="form-control" id="email" name="email" ng-model = "single_citizen.email" ng-required="true">
							    </div>
							    <div class="form-group col-md-6">
							      <label for="Birth_Date">Birth Date</label>
							      <input type="date" class="form-control" id="birth_Date" name="Birth_Date" value = "{[single_citizen.birth_date]}" ng-model="single_citizen.birth_date" ng-required="true">
							    </div>
							</div>
							<div class="form-row">
							    <div class="form-group col-md-6">
							      <label for="city">City</label>
							      <input type="text" class="form-control" id="city" name="city" 
							      ng-model="single_citizen.city" ng-required="true">
							    </div>
							    <div class="form-group col-md-6">
						      		<label for="pincode">pincode</label>
						      		<input type="text" class="form-control" id="pincode" name="pincode" ng-model="single_citizen.pincode" ng-required="true" maxlength="6"ng-pattern="/^[0-9]{0,7}$/">
								     <span ng-show="citizenform.pincode.$error.pattern" color='red'>Not a valid Pincode!</span>
						    	</div>
							</div>
							<div class="form-row">
								<div class="form-group col-md-12">
								    <label for="Address">Address</label>
								    <input type="text" class="form-control" id="Address" name="address" ng-model = "single_citizen.address" ng-required="true">
								</div>
							</div>
							<div class="form-row">
								<div class="form-group col-md-6">
								      <label for="Mobile">Mobile</label>
								      <input type="text" class="form-control" id="Mobile" name="mobile" ng-model="single_citizen.mobile" ng-required="true" maxlength="10" ng-pattern="/^[0-9]{0,10}$/">
								      <span ng-show="citizenform.mobile.$error.pattern" color='red'>Not a valid number!</span>
								</div>
							    <div class="form-group col-md-6">
							      <label for="Qualification">Qualification</label>
							      <input type="text" class="form-control" id="Qualification" name="qualification" ng-model="single_citizen.qualification" ng-required="true">
							    </div>
						    </div>
							    <div class="form-group text-center">
							    <button type="submit" ng-click = "citizenform.$valid && citizenUpdate(single_citizen.pk)" class="btn btn-primary btn-block">Update</button>
							    </div>
						</form>
					</div>
				</div>	
			</div>
		</div>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div>

	  </div>
	</div>
		<!-- End Madal -->
</div>

{% endblock %}

citizenapp/templates/update_form.html
{% extends 'base.html' %}
{% block title %}Citizen Form{% endblock %}
{% block body %}
	<div class= "container-fluid" ng-controller = 'citizen_controller'>
		<div class= "row">
			<div class="col-sm-0 col-lg-2 col-md-2"> 
				
			</div>
			<div class="col-sm-12 col-lg-8 col-md-8">
				<div class="panel panel-default">
				<div class="panel-heading"><strong>Citizen Registration</strong></div>
					<div class="panel-body">
						<form name = "citizenform" enctype="multipart/form-data">
						{% csrf_token %}
							<div class="form-row">
							    <div class="form-group col-md-6">
							      <label for="first_name">First Name</label>
							      <input type="text" class="form-control" name = "first_name" id="first_name" ng-model="data.first_name" ng-required="true">
							    </div>
							    <div class="form-group col-md-6">
							      <label for="last_name">Last Name</label>
							      <input type="" class="form-control" id="last_name" name = "last_name" ng-model="data.last_name" ng-required="true">
							    </div>
							</div>
							<div class="form-row">
							    <div class="form-group col-md-6">
							      <label for="email">Email</label>
							      <input type="email" class="form-control" id="email" name="email" ng-model = "data.email" ng-required="true">
							    </div>
							    <div class="form-group col-md-6">
							      <label for="Birth_Date">Birth Date</label>
							      <input type="date" class="form-control" id="birth_Date" name="Birth_Date" ng-model="data.birth_date" ng-required="true">
							    </div>
							</div>
							<div class="form-row">
							    <div class="form-group col-md-6">
							      <label for="city">City</label>
							      <input type="text" class="form-control" id="city" name="city" 
							      ng-model="data.city" ng-required="true">
							    </div>
							    <div class="form-group col-md-6">
						      		<label for="pincode">pincode</label>
						      		<input type="text" class="form-control" id="pincode" name="pincode" ng-model="data.pincode" ng-required="true" maxlength="6"ng-pattern="/^[0-9]{0,7}$/">
								     <span ng-show="citizenform.pincode.$error.pattern" color='red'>Not a valid Pincode!</span>
						    	</div>
							</div>
							<div class="form-row">
								<div class="form-group col-md-12">
								    <label for="Address">Address</label>
								    <input type="text" class="form-control" id="Address" name="address" ng-model = "data.address" ng-required="true">
								</div>
							</div>
							<div class="form-row">
								<div class="form-group col-md-6">
								      <label for="Mobile">Mobile</label>
								      <input type="text" class="form-control" id="Mobile" name="mobile" ng-model="data.mobile" ng-required="true" maxlength="10" ng-pattern="/^[0-9]{0,10}$/">
								      <span ng-show="citizenform.mobile.$error.pattern" color='red'>Not a valid number!</span>
								</div>
							    <div class="form-group col-md-6">
							      <label for="Qualification">Qualification</label>
							      <input type="text" class="form-control" id="Qualification" name="qualification" ng-model="data.qualification" ng-required="true">
							    </div>
						    </div>
						    <div class="form-row">
							    <div class="form-group col-md-4">
							      <label for="document"> Document Type</label>
										
									<select class="form-control" name="document_type" ng-model="data.document_type" ng-required="true">
								      <option>Select</option>
								      <option value="aadhar">Aadhar</option>
								      <option value="voter_id">Voter ID</option>
								      <option value="ration_card">Ration Card</option>
								      <option value="ration_card">Pan Card</option>
								    </select>

	    						</div>

	    						<div class="form-group col-md-6">
									<label for="document">Upload Document</label>
									<input type="file" class="form-control" name="document" file-model="myFile" ng-required="true" />
							      
							    </div>
							    <div class="form-group col-md-2" style="padding-top:22px">
							    	<button type="submit" ng-click = "citizenform.$valid && uploadFile(data.first_name, 'document')" class="btn btn-warning">Upload</button>
							    </div>
	    					</div>

	    					<div class='form-row'>
	    						<div class="form-group col-md-6">
									<label for="document">Upload Photo</label>
									<input type="file" class="form-control" name="document" file-model="myPhoto" ng-required="true" />
								</div>
							    <div class="form-group col-md-6" style="padding-top:22px">
							    	<button type="submit" ng-click = "citizenform.$valid && uploadFilePhoto(data.first_name, 'photo')" class="btn btn-warning">Upload</button>
					    		</div>
	    					</div>
	    					
						    <!-- <div class="form-row text-center"> -->
							    <div class="form-group text-center">
							    <button type="submit" ng-click = "citizenform.$valid && citizenUpdate()" class="btn btn-primary btn-block">Submit</button>
							    </div>
						    <!-- </div>  -->
						</form>
						<!-- <div class="form-row pull-right">
							    <div class="form-group col-md-6">
							    <button type="submit" ng-click = "add_citizen()" class="btn btn-primary">Submit</button>
							    </div>
						    </div> -->
					</div>
				</div>	
			</div>
		</div>
		<div class="col-sm-0 col-lg-2 col-md-2">
		</div>
	</div>
{% endblock %}